### ISSUE TITLE
outgoing breaks the Contact.message() function

### ISSUE THREAD

**Issue by czue** [caktus/rapidsms-threadless-router#9]
The rapidsms library expects outgoing to return whether or not the message was sent, and raises an error if not. As such, the router should return this.
https://github.com/rapidsms/rapidsms/blob/master/lib/rapidsms/models.py#L136

**Comment by czue** [comment]
https://github.com/caktus/rapidsms-threadless-router/pull/10

**Comment by mlavin** [comment]
Thanks again for the report and the fix @czue! This is available in the new `v0.1.4` release on PyPi.
